[book]
authors = ["Sagar Kumar Madala"]
language = "en"
src = "mds"

[build]
build-dir = "docs"

[output.html]
default-theme = "navy"
site-url = "/cpp-ebook-by-sagar/"
git-repository-url = "https://github.com/sagardesd/Cpp-ebook"
